############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Apartama Listings"
pageRef = "/listings"
weight = 2

[[main]]
name = "About"
pageRef = "/about"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1


[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 2
